export const classicEnigma: Enigma = [
  {
    id: "FE1",
    title: "Hush House",
    text: "Local records suggest that Hush House was a double monastery – a seventh-century foundation of both monks and nuns. There are two major traditions of its origin. This is the first.    \n “St Columba, with twelve companions, brought Christianity from Ireland to Scotland, and founded a monastery on the blessed isle of Iona, where his bones remained until the Northmen came. But in Brancrug Village they have it that St Columba brought a thirteenth companion, a 'hybrid beauty' named Rowena who was perhaps his tutor, perhaps his seducer, or perhaps his daughter. At his death, the monks sought to stone her for her impurities. She bore Columba's bones away so the monks would not have them (substituting, from tact or mischief, the bones of a horse). She brought them to Brancrug Isle, which even then was a hidden place, to make a double foundation of nuns and monks, and become its first abbess: but she would admit none to the order who was a virgin, nor innocent of any crime. Since then, Brancrug has been a refuge for all the world might consider impure.”\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the FE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "hush-house",
    image1: "https://imgur.com/siXDWFE.jpg",
    image2: "https://imgur.com/5t22Van.jpg",
  },
  {
    id: "FE2",
    title: "Hushery",
    text: "Aesthetics, necromancy, silence; the techniques used also by Reckoners.\n\n [In each of us there's a healing sadness.]\n\nYou've achieved the second degree, 'wisdom', of the FE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "hush-house-hushery",
    image1: "https://imgur.com/QyqNql2.jpg",
    image2: "https://imgur.com/GIPOwgz.jpg",
  },
  {
    id: "FE3",
    title: "Trist",
    text: "The change and the longing.\n\n[A tung of yung phanes.]\n\nYou've achieved the third degree, 'element', of the FE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "hushery-trist",
    image1: "https://imgur.com/HCG0GLz.jpg",
    image2: "https://imgur.com/rx8dg4I.jpg",
  },
  {
    id: "FE4",
    title: "Ericapaean",
    text: "A language of surpassing beauty and allusiveness, revealed through the ecstatic apprehensions of the Orphics, the Eleusinians, and the Sibyls of the Rhine. Ericapaean, these mystics claimed, allows the elaboration of hues, sensations and states of mind too subtle for grosser tongues.\n\n[A visitor to Hush House who catalogued a collection that in many histories was first-numbered among the lost. Alternatively, his chrismed unson.]\n\nYou've achieved the fourth degree, 'language', of the FE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "trist-ericapaean",
    image1: "https://imgur.com/Li1Ho4G.jpg",
    image2: "https://imgur.com/iGkkADU.jpg",
  },
  {
    id: "FE5",
    title: "Fraser Strathcoyne",
    text: "Out into the night! We escape unseen, but the next day there are reports of a fire at Strathcoyne's. Did someone knock a live coal on to the hearth-rug? Or did Strathcoyne destroy the place himself, as part of some larger scheme?…\n\n[Crow and mirror, sand-sown, oak-denying]\n\nYou've achieved the fifth degree, 'visitor', of the FE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ericapaean-fraser-strathcoyne",
    image1: "https://imgur.com/xF04tvP.jpg",
    image2: "https://imgur.com/L98xXGJ.jpg",
  },
  {
    id: "FE6",
    title: "Sea Holly",
    text: "Along the dunes by the skeleton abbey, blue-silver, black-steel.\n\n[Dr Hengerst Department of English and Philology University College of Swansea Singleton Abbey Mumbles Road Sketty Swansea]\n\nYou've achieved the sixth degree, 'flower', of the FEATHER direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "christopher-strathcoyne-sea-holly",
    image1: "https://imgur.com/dEA3p6A.jpg",
    image2: "https://imgur.com/KlCQgCk.jpg",
  },
  {
    id: "FE7",
    title: "Rowena",
    text: "ST RHONWEN TRUST: a charitable trust established in 1922 for the advancement of education, chiefly through scholarships for promising young talents…\n\n[Coseley never forgave Husher, but at last he respected him.]\n\nYou've achieved the seventh degree, 'protectress', of the FEATHER direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "sea-holly-rowena",
    image1: "https://imgur.com/5BRwuN6.jpg",
    image2: "https://imgur.com/fpIe83e.jpg",
  },
  {
    id: "FE8",
    title: "Towards A Fundamental Aesthetic",
    text: "Techniques for perception and analysis which permit invidious and apocalyptic conclusions. Probably the most assiduously suppressed book in history. The entire run was destroyed – even the presses were melted and dispersed – but the manuscript edition has survived.\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, 'wise', of the FEATHER direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "rowena-towards-a-fundamental-aesthetic",
    image1: "https://imgur.com/n2wrIJ0.jpg",
    image2: "https://imgur.com/n7tybaT.jpg",
  },
  {
    id: "SC1",
    title: "Labyrinth Of Lions",
    text: "The Labyrinth of Lions teaches horomachistry and Illumination. In the First History, it was established as a labyrinth-fortress in the lands of the Shadowless King-of-Kings. When days were yet undivided, it lay under the hand of the Sun. Now the Lionsmith lends his protection. For twenty-two centuries, mystics, strategists, and sorrowful warriors have all sought to penetrate its coils in an attempt to advance their understanding.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the SC direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "labyrinth-of-lions",
    image1: "https://imgur.com/cQJAxFE.jpg",
    image2: "https://imgur.com/e1nk4Kc.jpg",
  },
  {
    id: "SC2",
    title: "Illumination",
    text: "Mystical exercises to purify and illuminate the self and its surroundings. Relic Rites of the Unconquered Sun, mirrors and light sources, the Glory.\n\n[We have all benefited from the Glory's gifts.]\n\nYou've achieved the second degree, 'wisdom', of the SC direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "labyrinth-of-lions-illumination",
    image1: "https://imgur.com/WZRIzDj.jpg",
    image2: "https://imgur.com/QwpDCh3.jpg",
  },
  {
    id: "SC3",
    title: "Phost",
    text: "Sight, perception, inspiration, all the Glory's gifts.\n\n[One tongue, many eyes.]\n\nYou've achieved the third degree, 'element', of the SC direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "illumination-phost",
    image1: "https://imgur.com/BhjaCzA.jpg",
    image2: "https://imgur.com/QqYgmMG.jpg",
  },
  {
    id: "SC4",
    title: "Cracktrack",
    text: "In the Tracks of Beasts, in the Convolutions of his own Carapace, in Egg-vein and Shell-shadow, the Many-Eyed One found the Signs which can be History.\n\n[A visitor to the Labyrinth, torch-named, who can never return, only alight]\n\nYou've achieved the fourth degree, 'language', of the SC direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "phost-cracktrack",
    image1: "https://imgur.com/5lh8Rtq.jpg",
    image2: "https://imgur.com/aiyr0jA.jpg",
  },
  {
    id: "SC5",
    title: "Everett Lapidoth",
    text: "Fulgents are confined to the Mansus and the Bounds, but they have considerable influence there. They're well-placed to shape and send dreams. Fulgents avoid the Wood. It's confusing and unpleasant, and the Wood-names there will devour them if they can. There are risks in the House, too, from Mansus-names, but that's manageable, and they have allies in the House…\n\n[Dapple and motley, shepherd-sung, swine-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the SC direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "cracktrack-everett-lapidoth",
    image1: "https://imgur.com/mbwiUNK.jpg",
    image2: "https://imgur.com/eothffq.jpg",
  },
  {
    id: "SC6",
    title: "Moly",
    text: "Power-plucked from sacred soil where old blood was shed. Shadow, then snow.\n\n[The King of the World made his dedication to the Evening Star at the Gate of Gods. She lies long in the land of the Lionsmith's Labyrinth.]\n\n\n\nYou've achieved the sixth degree, 'flower', of the SCALE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "everett-lapidoth-moly",
    image1: "https://imgur.com/fmtV996.jpg",
    image2: "https://imgur.com/vV0CQeL.jpg",
  },
  {
    id: "SC7",
    title: "Lamma",
    text: "“The Khusgai that we slew. On their standard they bore a silver hand. We took it as a trophy and it graces now the standard of my regiment. I still write that – I will not strike it out – but of course I cannot no longer claim that honour. It graces now the standard of the Poona Horse. If you ask to see it I think they will show it to you – if you use Malcolmson's name and not mine. It is older than the regiment – as old I think as England. But no older. There is a lesson in it. Greatest among the powers who illuminate is one called Watchman. He it is who says 'Mercy is found only in shadow.' But he does not say that mercy is nowhere found; and shadows lie long at the Labyrinth of Lions.”\n\n[A sleeping gentleman and a solar majuscule.]\n\n\n\nYou've achieved the seventh degree, 'protectress', of the SCALE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "moly-lamma",
    image1: "https://imgur.com/0rpA3th.jpg",
    image2: "https://imgur.com/IeQnymm.jpg",
  },
  {
    id: "SC8",
    title: "The Man With The Plan",
    text: "Beneath the Church of the Holy Belt in Emesa/Homs, there is, as legend relates, a secret room which was also the first church, consecrated (in 59) – perhaps as a Christian shrine by Paul the Apostle, perhaps as an Invictine shrine by Saul the Illuminated. There in a sarcophagus of black corundum lies Elagabalus, accursed of Janus, neither Long nor mortal, neither man nor woman, neither real nor imagined. On his light-suffused skin is made manifest the Sun-in-Splendour's grand design… or a monstrous lie.\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, 'wise', of the SCALE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "lamma-the-man-with-the-plan",
    image1: "https://imgur.com/R8drZ80.jpg",
    image2: "https://imgur.com/jJCZdFB.jpg",
  },
  {
    id: "SC8b",
    title: "Uncial Elagabaline",
    text: "[[unknown- for now, at least]]\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, 'otherwise', of the SCALE (b) direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "lamma-uncial-elagabaline",
    image1: "https://imgur.com/R8drZ80.jpg",
    image2: "https://imgur.com/jJCZdFB.jpg",
  },
  {
    id: "HE1",
    title: "Crossrow",
    text: "In a garden city of the far West, in an establishment of uncertain age, in a gloriously decaying garden-mansion, you can find perhaps the only library in the world where silence is discouraged. The Watchman and the Vagabond are venerated there, and Sunset Celia's shrine is aligned each day so the dawn may be greeted with music. It claims to be the site of the first Roost, though it's by no means the only place to make that claim. The lights of the house are never extinguished, and its hospitalities, if you can find the place at all, are generally both warm and bright. Perhaps we'll see you there.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the HE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "crossrow",
    image1: "https://imgur.com/Cn0xgs6.jpg",
    image2: "https://imgur.com/xYuz9Qe.jpg",
  },
  {
    id: "HE2",
    title: "Birdsong",
    text: "Music, riddles, miscellany. The matters of the Roost, of Ghirbi, of the Leak, the Vagabond, the Carapace Cross and a hundred and five others.\n\n[We do not cease until we are ceased.]\n\nYou've achieved the second degree, 'wisdom', of the HE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "crossrow-birdsong",
    image1: "https://imgur.com/1qesLat.jpg",
    image2: "https://imgur.com/0oBnUhS.jpg",
  },
  {
    id: "HE3",
    title: "Chor",
    text: "Energy and tenacity; rhythm.\n\n[This tongue is the stone and it is not the stone, the thumb-sucking slayer-stone.]\n\nYou've achieved the third degree, 'element', of the HE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "birdsong-chor",
    image1: "https://imgur.com/xMe9RCy.jpg",
    image2: "https://imgur.com/xQes0dk.jpg",
  },
  {
    id: "HE4",
    title: "Ramsund",
    text: "This language has been called 'mantiq al-tair' and 'lenga aucel' and 'the speech of birds' and 'Ramsund' and 'the hazelnut tongue', but it's a language of secrets, and its true name may never be used. The aviform Hours use it at their Roost, or so the story goes.\n\n[A visitor to Crossrow who did not write himself. Perhaps the opposite.]\n\nYou've achieved the fourth degree, 'language', of the HE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "chor-ramsund",
    image1: "https://imgur.com/9q3T6L9.jpg",
    image2: "https://imgur.com/jPVbhJe.jpg",
  },
  {
    id: "HE5",
    title: "Arun Peel",
    text: "Once Peel had peeled itself, it had the ink it needed to write the Tantra. It had to face the wrath of its fellows...\n\n[Scent and song, glory-garbed, death-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the HE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ramsund-arun-peel",
    image1: "https://imgur.com/FZICJaZ.jpg",
    image2: "https://imgur.com/I5iLfMT.jpg",
  },
  {
    id: "HE6",
    title: "Trumpet Lily",
    text: "There's always a rebirth. We can't do anything much about that.\n\n[SANCTA CAECILIA ORA PRO NOBIS PEREGRINIS NUNC ET IN HORA TRANSITUS NOSTRI]\n\nYou've achieved the sixth degree, 'flower', of the HEART direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "arun-peel-trumpet-lily",
    image1: "https://imgur.com/j5qHsii.jpg",
    image2: "https://imgur.com/8RDh8uy.jpg",
  },
  {
    id: "HE7",
    title: "Sunset Celia",
    text: "No other Maid loves music so. In older texts she has been called Caelia the Elagabaline. Perhaps she was his daughter? Perhaps Tryphon's sister? Perhaps, like the Watchman himself, she is like a shadow cast by two candles.\n\n[There is a History where Alexander defeated first the Great Knot of Sabazos, and then the King of Kings. There is another History where, instead, he learnt from them. How many more? If we curl our hands into the correct shapes, we may yet understand. One of each, precious of the moon and of the sea.]\n\nYou've achieved the seventh degree, 'protectress', of the HEART direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "trumpet-lily-sunset-celia",
    image1: "https://imgur.com/3YcPV0u.jpg",
    image2: "https://imgur.com/NytXJ9S.jpg",
  },
  {
    id: "HE8",
    title: "The Turquoise Hand",
    text: "A calligraphic manual of Ramsund which employs as exemplar-text Farid ud-Din's 'Conference of the Birds'. Its commentary, illustrations and interleavings carry revelations never intended in the original.\n\n[Not until there are enough here. But look around.]\n\nYou've achieved the eighth degree, 'wise', of the HEART direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "sunset-celia-the-turquoise-hand",
    image1: "https://imgur.com/NjgJDs7.jpg",
    image2: "https://imgur.com/bHeQ3Ho.jpg",
  },
  {
    id: "KN1",
    title: "Tomb Of Lies",
    text: "The Great Hooded Princes do not reveal their library's location. Those few permitted entry will say only that it's 'west of the Lion, and north of Victory'. It contains knowledge on the ways and foundations of the Mansus; on the Fifth History, and above all on Knock lore. The Princes do not say 'Knowledge is Power', but rather, 'Power is Knowledge.' Relationships between the Princes and the Mother of Ants are strained, and the Tomb lies under the hand of the Horned Axe.\n\n[After this place, a suitable wisdom.]\n\n\n\nYou've achieved the first degree, 'library', of the KN direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "tomb-of-lies",
    image1: "https://imgur.com/Pqp51Ga.jpg",
    image2: "https://imgur.com/vjOWlw2.jpg",
  },
  {
    id: "KN2",
    title: "Nyctodromy",
    text: "'Travelling at night.' The ways and byways of other worlds.\n\n[Sometimes our reach exceeds our grasp, but in dreams our grasp can exceed our reach.]\n\nYou've achieved the second degree, 'wisdom', of the KN direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "tomb-of-lies-nyctodromy",
    image1: "https://imgur.com/gXUXNG6.jpg",
    image2: "https://imgur.com/yR59uHT.jpg",
  },
  {
    id: "KN3",
    title: "Fet",
    text: "That part of us which dreams. The connection to the Mansus.\n\n[This tongue, entrance into secret light.]\n\nYou've achieved the third degree, 'element', of the KN direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "nyctodromy-fet",
    image1: "https://imgur.com/Kd4MfKg.jpg",
    image2: "https://imgur.com/Faq9bSz.jpg",
  },
  {
    id: "KN4",
    title: "Vak",
    text: "Before gods arose from blood, before ever ape stood upright, this was the language heard in the House of the Sun…. 'I am Vak,' the Peacock Door boasted, 'both the tongue and the Goddess. I am the only entrance into secret light. I was worshipped before you upright apes, and I will be still when all of you are ugly ash. Listen, and I will prove it.\n\n[A visitor to the Tomb who knew the value of seventy-seven winks.]\n\nYou've achieved the fourth degree, 'language', of the KN direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "fet-vak",
    image1: "https://imgur.com/KOx49si.jpg",
    image2: "https://imgur.com/SPEPml5.jpg",
  },
  {
    id: "KN5",
    title: "Dagmar Von Nagelsburg",
    text: "“So here you go, bill, book, all we're missing is a candle, ha ha! I'll be by again for the Equinox. Could use your help on a thing with the Mausoleum. And the Club, actually. Bit of a business, there…”\n\n[Wing and huntress, bark-blessing, drouth-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the KN direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "vak-dagmar-von-nagelsburg",
    image1: "https://imgur.com/O2vswF7.jpg",
    image2: "https://imgur.com/jvg3wCI.jpg",
  },
  {
    id: "KN6",
    title: "Phalaenopsis",
    text: "The Princes favor this flower.\n\n[Fair to Friends, Horned to Foes, to Day-Flyers Scaled, by Hawthorn Homed.]\n\nYou've achieved the sixth degree, 'flower', of the KNOCK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "dagmar-von-nagelsburg-phalaenopsis",
    image1: "https://imgur.com/Aix5M7F.jpg",
    image2: "https://imgur.com/LI0h0wC.jpg",
  },
  {
    id: "KN7",
    title: "Xenodice",
    text: "“There are strict limits on the number of Hours, Names, Long and Know. Strict limits. Seven Names for each Hour, seven Long for each Name, seven Know for each Long. Since there can only ever be exactly thirty Hours, we can do the sums and work it all out perfectly. Except, no matter which way I do the sums, it never comes to thirty Hours. If I include the ones in Nowhere, it's twenty-eight. If I'm a bit more speculative, it's thirty-four. The Chancel has its accounted thirty, Xenodice told me once, but Xenodice doesn't share her mistress' secrets.”\n\n[“The Cross died not but passed within.” Strathcoyne knew, and Strathcoyne learnt almost too late. Gore's stories might have shown the way, but Gore looked too deep, past the truth.]\n\nYou've achieved the seventh degree, 'protectress', of the KNOCK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "moth-orchid-xenodice",
    image1: "https://imgur.com/U0hYLws.jpg",
    image2: "https://imgur.com/zmMomhR.jpg",
  },
  {
    id: "KN8",
    title: "The Writing On The Wall",
    text: "The histories of the Carapace Cross, as recorded on the walls of the Mansus and transcribed into a book of ninety-nine pages by one known only as 'cc'. This book does not exist, but it can be read in sleep, if one pulverizes and then consumes a hallowed diamond. Certain fragments do exist, when jotted down on waking.\n\n[Not until there are enough here. But look around.]\n\nYou've achieved the eighth degree, 'wise', of the KNOCK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "xenodice-the-writing-on-the-wall",
    image1: "https://imgur.com/RhZP3QO.jpg",
    image2: "https://imgur.com/o2RJBTq.jpg",
  },
  {
    id: "MO1",
    title: "Haustorium",
    text: "An enclave beyond the Evening Isles (and in the Bounds) established by an alliance of Catholic friars with Incan magicians. It preserves those things that are elsewhere considered unwise to preserve. The Haustorium lies beneath the hand of the Crowned Growth. It is in no way a safe place to visit, nor even really to communicate with. It's probably not even a good idea to dream about it.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the MO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "haustorium",
    image1: "https://imgur.com/Frmejt4.jpg",
    image2: "https://imgur.com/6lu1Vjh.jpg",
  },
  {
    id: "MO2",
    title: "Skolekosophy",
    text: "'The study of things that should not be studied'. Perversions and abrasions, Worms, Nowhere; earthquakes.\n\n[\"Without speech no answer is possible.\" This is suppressed by the White Door, or perhaps even left outside it, as a sword outside a king's hall or as a key in the door.]\n\nYou've achieved the second degree, 'wisdom', of the MO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "haustorium-skolekosophy",
    image1: "https://imgur.com/XlbvZh4.jpg",
    image2: "https://imgur.com/pOafjm6.jpg",
  },
  {
    id: "MO3",
    title: "Shapt",
    text: "Eloquence and understanding. The door opens both ways.\n\n[This honey'd tongue]\n\nYou've achieved the third degree, 'element', of the MO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "skolekosophy-shapt",
    image1: "https://imgur.com/vGWD23I.jpg",
    image2: "https://imgur.com/yD4Hvm9.jpg",
  },
  {
    id: "MO4",
    title: "Hyksos",
    text: "The Shepherd-Kings brought this speech west from Canaan to use in their wards and snares. Had they never come to Egypt, they might never found a way to write it; given its addictive qualities, that might have been for the best.\n\n[A visitor to the Haustorium who bore away a golden treasure.]\n\nYou've achieved the fourth degree, 'language', of the MO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "shapt-hyksos",
    image1: "https://imgur.com/AeUBs7w.jpg",
    image2: "https://imgur.com/oI5Jog3.jpg",
  },
  {
    id: "MO5",
    title: "Lord Gristwood",
    text: "Once upon a time, a very bad man encoded very bad secrets into the charming illustrations of a book of charming stories. Wake the pictures, and you will see…\n\n[Blood and flesh, needle-loving, sun-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the MO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "hyksos-lord-gristwood",
    image1: "https://imgur.com/uAYEbSM.jpg",
    image2: "https://imgur.com/CPxEvsf.jpg",
  },
  {
    id: "MO6",
    title: "Snow Plant",
    text: "There are other modes than ours\n\n[vi. 'A Child's Treasury of Golden Afternoons', Jacob Gristwood. Clearly I am aware of the Standing Incineration Order on this work but this may be the only copy still in existence and the skolekosophic resources available to the Branch are frankly embarrassing in their paucity. After a detailed examination, not to mention discussion with my very good friend the Dottore, I have determined that it is much too valuable to be destroyed. Retained.]\n\nYou've achieved the sixth degree, 'flower', of the MOON direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "lord-gristwood-snow-plant",
    image1: "https://imgur.com/VXJRK5n.jpg",
    image2: "https://imgur.com/4IoTRSj.jpg",
  },
  {
    id: "MO7",
    title: "Robigo",
    text: "“If you are dead but 'uplifted by green', that's the Ring-Yew's blessing. (The Crowned Growth offers a similar but nastier benefit.) This is how Burgeoning Risen come about, but there are different degrees of sentience and freedom depending on which growths are involved. The consciousness of one 'uplifted by green' is always greatly altered, though – they never really seem like the same person. They may have dregs of their original souls, but these are often replaced by something else.” – Detective-Ostiary Wheelock, An Exorcist's Field Manual\n\n[This is a proposal we would consider only in the most extreme circumstances. Where is the manner of the vein?]\n\nYou've achieved the seventh degree, 'protectress', of the MOON direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "sarcodes-robigo",
    image1: "https://imgur.com/RRBjzcH.jpg",
    image2: "https://imgur.com/UoXRHJs.jpg",
  },
  {
    id: "MO8",
    title: "A Childs Treasury Of Golden Afternoons",
    text: "Once upon a time, a very bad man encoded very bad secrets into the charming illustrations of a book of charming stories. Wake the pictures, and you will see.\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, 'wise', of the MOON direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "robigo-a-childs-treasury-of-golden-afternoons",
    image1: "https://imgur.com/Qg57fi2.jpg",
    image2: "https://imgur.com/Sxp5gIn.jpg",
  },
  {
    id: "BL1",
    title: "Grove Of Green Immortals",
    text: "This is a mountain-monastery of renegade Taoists. They specialise in horticulture and medicine, in Moth and Heart lore, in the gossip of the Hours, all under the hand of the Applebright... but the Grove is supposed to be safe to visit, because of the arrangement the scholars and the Applebright have made.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the BL direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "grove-of-green-immortals",
    image1: "https://imgur.com/YogmpWV.jpg",
    image2: "https://imgur.com/3rWUlet.jpg",
  },
  {
    id: "BL2",
    title: "Bosk",
    text: "The lore of the primaeval wood; rarely written, often felt.\n\n[Hath each their darkness.]\n\nYou've achieved the second degree, 'wisdom', of the BL direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "grove-of-green-immortals-bosk",
    image1: "https://imgur.com/MPxhlCu.jpg",
    image2: "https://imgur.com/dvcw83m.jpg",
  },
  {
    id: "BL3",
    title: "Ereb",
    text: "Pride, compassion; hatred and fear.\n\n[This tongue, silver-caging.]\n\nYou've achieved the third degree, 'element', of the BL direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "bosk-ereb",
    image1: "https://imgur.com/MyjqRjq.jpg",
    image2: "https://imgur.com/M1MucCF.jpg",
  },
  {
    id: "BL4",
    title: "Killasimi",
    text: "If there is speech in Nowhere; if there is a language used by the Dead; if the House of the Moon has a native tongue; then it must be Killasimi. If none of this is true, it is still not a language to be spoken in daylight. Each word breathes woe. Read it, as they say, and weep.\n\n[A visitor to the Grove whose meals came winged east.]\n\nYou've achieved the fourth degree, 'language', of the BL direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ereb-killasimi",
    image1: "https://imgur.com/dUzu8w8.jpg",
    image2: "https://imgur.com/amMwSsi.jpg",
  },
  {
    id: "BL5",
    title: "Zulfiya Zakirova",
    text: "“The Mother pierces,\" Zulfiya says conversationally, tugging at her fingernails. \"The Witch demands, and the Sister dissolves...”\n\n[Flask and cup, moon-sown, malady-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the BL direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "killasimi-zulfiya-zakirova",
    image1: "https://imgur.com/PqQXJs1.jpg",
    image2: "https://imgur.com/LsEBrl1.jpg",
  },
  {
    id: "BL6",
    title: "Osmanthus",
    text: "The Serapeum has its black tea, the Yeshiva its healing tisanes, but the Grove dries their own preparations.\n\n[Eagle-harried, eagle-born, nectar's heart, blood's fair fount. Later her name is fitting.]\n\nYou've achieved the sixth degree, 'flower', of the BLOOD direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "zulfiya-zakirova-osmanthus",
    image1: "https://imgur.com/KdseOOc.jpg",
    image2: "https://imgur.com/OR0CBHU.jpg",
  },
  {
    id: "BL7",
    title: "Idonea",
    text: "A Lovely who consumes an Ivory becomes an Ivory. A Lovely who consumes a Thirstly becomes a Thirstly. A Lovely who consumes a Name of another Hour might take its place. An incident where a Lovely consumes a Name of the Crowned Growth was described in some detail by Malskær in 'The Intimations of Skin', but Malskær did not record the name or the final condition of the consumption's outcome.\n\n[There had to be a first time. We can learn from it. The Writer on the Walls can begin it, but only if he is suitably hybridised with the doctor's inception.]\n\nYou've achieved the seventh degree, 'protectress', of the BLOOD direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "osmanthus-idonea",
    image1: "https://imgur.com/g7rei5f.jpg",
    image2: "https://imgur.com/9zBL0vl.jpg",
  },
  {
    id: "BL8",
    title: "Kopralith Omphalos",
    text: "What is this? A tufted fossil of silken fibre, big as a child. Something consumed, and something was consumed. If we interpret its interweavings, we might understand.\n\n[Not until there are enough here. But look around.]\n\nYou've achieved the eighth degree, 'wise', of the BLOOD direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "idonea-kopralith-omphalos",
    image1: "https://imgur.com/WOBJIhW.jpg",
    image2: "https://imgur.com/Roz1J5i.jpg",
  },
  {
    id: "FO1",
    title: "Monastery Of The Fifth Cup",
    text: "“Spending on feasting and wine is better than hoarding our substance. That which we give makes us richer, that which is hoarded is lost.” A quietly unorthodox monastery with a tendency to apophatic theology and a strong winemaking tradition. Ithastry is their particular domain, but they're also respected for their boskiness. Of all the nine great storehouses of the wisdoms, the Fifth Cup possesses the fewest actual books. Most of their knowledge is encoded in their wines, or in the devices in their triple-locked cellars, or in the skulls of the brethren. “Never spoken, never stolen.”\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "monastery-of-the-fifth-cup",
    image1: "https://imgur.com/DbXjOEq.jpg",
    image2: "https://imgur.com/Travzja.jpg",
  },
  {
    id: "FO2",
    title: "Ithastry",
    text: "Crafting, locksmithing, pyrotechnics: the arts that alter. Mirror alloys, the Noble Endeavour, the Corrivality.\n\n[All the living have it. Many of the dead retain it. Books have only this… at least those books that can be trusted.]\n\nYou've achieved the second degree, 'wisdom', of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "monastery-of-the-fifth-cup-ithastry",
    image1: "https://imgur.com/rAtu4Ab.jpg",
    image2: "https://imgur.com/jXHEkqo.jpg",
  },
  {
    id: "FO3",
    title: "Wist",
    text: "Name, memory, that part which remains.\n\n[A tongue twice never Lydian.]\n\nYou've achieved the third degree, 'element', of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ithastry-wist",
    image1: "https://imgur.com/7c7TvHd.jpg",
    image2: "https://imgur.com/CRoHFAe.jpg",
  },
  {
    id: "FO4",
    title: "Fucine",
    text: "A people lived east of the lost lake Fucino. Horace warned that theirs was the land of witches. This was their language, called by some 'the dry tongue' and by others 'the tongue of witches'.\n\n[A tricksy sheep-pot visitor, or guest.]\n\nYou've achieved the fourth degree, 'language', of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "wist-fucine",
    image1: "https://imgur.com/g5Wan53.jpg",
    image2: "https://imgur.com/8WA9pIK.jpg",
  },
  {
    id: "FO5",
    title: "Medea",
    text: "“I was,” she says. “Now I'm not.”\n\n[Gifts and bane, birth-feasting, delusion-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "fucine-medea",
    image1: "https://imgur.com/wekbgKb.jpg",
    image2: "https://imgur.com/DJkeja9.jpg",
  },
  {
    id: "FO6",
    title: "Lenten Rose",
    text: "Winter turns her head until we see spring's face.\n\n[Once in the Wood we call a visit. Twice in the Wood we call a journey. Thrice, we call coming home.]\n\nYou've achieved the sixth degree, 'flower', of the FORGE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "medea-lenten-rose",
    image1: "https://imgur.com/d59VKNq.jpg",
    image2: "https://imgur.com/PuLG6jc.jpg",
  },
  {
    id: "FO7",
    title: "Aunt Mopsy",
    text: "Aunt Mopsy c/o Osier House Publishing 14 Plover Street Kerisham G.B.\n\n[The black-eared hound knew well its taste, but never sought it. High it fell in the eagle-scarred place. Honestly, if you're ever inclined to wait for more clues, wait for more clues for this.]\n\nYou've achieved the seventh degree, 'protectress', of the FORGE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "lenten-rose-aunt-mopsy",
    image1: "https://imgur.com/hGUPv2T.jpg",
    image2: "https://imgur.com/vvNThgz.jpg",
  },
  {
    id: "FO8",
    title: "Amiranis Beteli",
    text: "Who gave us fire? Who gave us steel? In this sky-cast wist-stone, we see the long evidence for both.\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, \"wise\", of the FO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "aunt-mopsy-amiranis-beteli",
    image1: "https://imgur.com/5bB4RbI.jpg",
    image2: "https://imgur.com/Ss9jKGL.jpg",
  },
  {
    id: "RO1",
    title: "Invisible Serapeum",
    text: "“The first and irreparable disaster was the fall of the Lantern.” Perhaps thanks to the protection of the Forge of Days, the Serapeum has survived the long decline of its parent library. Or perhaps it's just that the Serapeum is invisible to the dull-sighted even once they're inside it. The Forge does not usually favour libraries, but the Serapeum specialises in Forge lore and horomachistry, and favours non-combustible media.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "invisible-serapeum",
    image1: "https://imgur.com/dOS9adE.jpg",
    image2: "https://imgur.com/hRLnyFJ.jpg",
  },
  {
    id: "RO2",
    title: "Horomachistry",
    text: "The laws and contentions of the Hours and their emanations. What makes us what we are. Forbiddings and laws and the proper ways to proper roles.\n\n[What when unobserved?]\n\nYou've achieved the second degree, 'wisdom', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "invisible-serapeum-horomachistry",
    image1: "https://imgur.com/JnEigLL.jpg",
    image2: "https://imgur.com/qMEkB7R.jpg",
  },
  {
    id: "MO6a",
    title: "Sarcodes",
    text: "There are other modes than ours\n\n[vi. 'A Child's Treasury of Golden Afternoons', Jacob Gristwood. Clearly I am aware of the Standing Incineration Order on this work but this may be the only copy still in existence and the skolekosophic resources available to the Branch are frankly embarrassing in their paucity. After a detailed examination, not to mention discussion with my very good friend the Dottore, I have determined that it is much too valuable to be destroyed. Retained.]\n\nYou've achieved the sixth degree, 'flower', of the MOON direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "lord-gristwood-sarcodes",
    image1: "https://imgur.com/VXJRK5n.jpg",
    image2: "https://imgur.com/4IoTRSj.jpg",
  },
  {
    id: "KN6a",
    title: "Moth Orchid",
    text: "The Princes favor this flower.\n\n[Fair to Friends, Horned to Foes, to Day-Flyers Scaled, by Hawthorn Homed.]\n\nYou've achieved the sixth degree, 'flower', of the KNOCK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "dagmar-von-nagelsburg-moth-orchid",
    image1: "https://imgur.com/Aix5M7F.jpg",
    image2: "https://imgur.com/LI0h0wC.jpg",
  },
  {
    id: "RO3",
    title: "Character",
    text: "The capacity for meaningful choice.\n\n[A tongue of bowls and rolls.]\n\nYou've achieved the third degree, 'element', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "horomachistry-character",
    image1: "https://imgur.com/gOcmhEH.jpg",
    image2: "https://imgur.com/qvHNW8p.jpg",
  },
  {
    id: "RO3a",
    title: "Mettle",
    text: "The capacity for meaningful choice.\n\n[A tongue of bowls and rolls.]\n\nYou've achieved the third degree, 'element', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "horomachistry-mettle",
    image1: "https://imgur.com/gOcmhEH.jpg",
    image2: "https://imgur.com/qvHNW8p.jpg",
  },
  {
    id: "RO4",
    title: "Deep Mandaic",
    text: "The most secret script of the innermost rites of the deep sects of the deep desert. The birth-tongue, it is claimed, of the Mother of Ants herself.\n\n[A visitor to the Serapeum of a long-noted significant absence, from a city of thundering milk.]\n\nYou've achieved the fourth degree, 'language', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "character-deep-mandaic",
    image1: "https://imgur.com/wd5ZNC2.jpg",
    image2: "https://imgur.com/eYJZuED.jpg",
  },
  {
    id: "RO5",
    title: "Ibn Al Adim",
    text: "The good doctor has an interest in overlooked histories. He's a newcomer to the city, but speaks fondly of his memories of previous visits, long ago...\n\n[Shard and serpent, fragrance-crowned, day-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the RO direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "deep-mandaic-ibn-al-adim",
    image1: "https://imgur.com/pfbAPIs.jpg",
    image2: "https://imgur.com/V5EdKAi.jpg",
  },
  {
    id: "RO6",
    title: "Jasmine Sambac",
    text: "In Alexandria, where the white night-flowers shed their scent, you're most likely to find entrances to the Serapeum. But it's never very likely.\n\n[The Isle that is Veiled, the Scar that Soothes.]\n\nYou've achieved the sixth degree, 'flower', of the ROSE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ibn-al-adim-jasmine-sambac",
    image1: "https://imgur.com/lo3ciTM.jpg",
    image2: "https://imgur.com/FNyDAhT.jpg",
  },
  {
    id: "RO7",
    title: "Eskhara-Meligounis",
    text: "“Was Eskhara-Meligounis once a Name of the Twins? Certainly it would explain why the Twins scraped the barrel so for the Names they own today.”\n\n[There's a clouded but refulgent truth in these images – from the times before the Sun was divided. One day soon you'll understand it..]\n\nYou've achieved the seventh degree, 'protectress', of the ROSE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "jasmine-sambac-eskhara-meligounis",
    image1: "https://imgur.com/9oIKiEb.jpg",
    image2: "https://imgur.com/VjFTNwG.jpg",
  },
  {
    id: "RO8",
    title: "Book Of Suns",
    text: "Set down with reverence before the Intercalate, by one who understood. Glory.\n\n[Not until there are enough here. But look around.]\n\nYou've achieved the eighth degree, 'wise', of the ROSE direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "eskhara-meligounis-book-of-suns",
    image1: "https://imgur.com/gxEptoJ.jpg",
    image2: "https://imgur.com/JTED51s.jpg",
  },
  {
    id: "SK1",
    title: "Yeshiva Tigris",
    text: "For fifty years a secret yeshiva in Tiflis has taught the Four Traditions of the Bei Ilai: the imprisonment of spirits, the expulsion of monsters, the conclusion of tenacious curses and the sealing of troublesome portals. The YT has had a long and very beneficial understanding with the Fifth Cup, but for the last twenty years has been engaged in a bitter and incomprehensible feud, approximately because someone hasn't returned a book but no one can agree who or what. They specialise in preservation lore, with a strong second string in skolekosophy.\n\n[After this place, a suitable wisdom.]\n\nYou've achieved the first degree, 'library', of the SK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "yeshiva-tigris",
    image1: "https://imgur.com/m1ELMja.jpg",
    image2: "https://imgur.com/G012Owh.jpg",
  },
  {
    id: "SK2",
    title: "Preservation",
    text: "Healing and restoration; Commandments for the Preservation of All that Exists; Relic Rites of the Sisterhood of the Knot; legacy rites of the Gods-from-Stone.\n\n[Nothing without.]\n\nYou've achieved the second degree, 'wisdom', of the SK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "yeshiva-tigris-preservation",
    image1: "https://imgur.com/Ba12kKv.jpg",
    image2: "https://imgur.com/AatKj7A.jpg",
  },
  {
    id: "SK3",
    title: "Health",
    text: "The dwelling-place of the soul.\n\n[The hand enacts the tongue.]\n\nYou've achieved the third degree, 'element', of the SK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "preservation-health",
    image1: "https://imgur.com/D3AoVqb.jpg",
    image2: "https://imgur.com/oSkWgRi.jpg",
  },
  {
    id: "SK4",
    title: "Sabazine",
    text: "There is a History where Alexander defeated first the Great Knot of Sabazos, and then the King of Kings. There is another History where, instead, he learnt from them. How many more? If we curl our hands into the correct shapes, we may yet understand.\n\n[A visitor to the Yeshiva from whose body flowers shall grow...]\n\nYou've achieved the fourth degree, 'language', of the SK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "health-sabazine",
    image1: "https://imgur.com/jnQ4Jzr.jpg",
    image2: "https://imgur.com/MJzGdok.jpg",
  },
  {
    id: "SK5",
    title: "Moishe Farouk",
    text: "“My darling Moishe will be there to greet me on the other side. Death shall mend one of the two great pains in my life: to live in such a beautiful city, but for so many years without him…”\n\n[Flush and fortune, myrmid-beguiling, devil-denying.]\n\nYou've achieved the fifth degree, 'visitor', of the SK direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "sabazine-moishe-farouk",
    image1: "https://imgur.com/4eKd6w3.jpg",
    image2: "https://imgur.com/aKL1rQn.jpg",
  },
  {
    id: "SK6",
    title: "Aglaophotis",
    text: "Dioscorides would have been permitted to enter. There's no doubt of that.\n\n[Stronger and sharper than bronze Fiercer than mere amazons Tempted by feet She tried to be sweet But she hated the song of the swans]\n\nYou've achieved the sixth degree, 'flower', of the SKY direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "moishe-farouk-aglaophotis",
    image1: "https://imgur.com/xHkJGIW.jpg",
    image2: "https://imgur.com/00qA7W7.jpg",
  },
  {
    id: "SK7",
    title: "Skadi",
    text: "“The Madrugad and the Witch-and-Sister are not counted among the Chancel, but they are more closely associated than most. And the Madrugad has been known to send her huntress after Hours-that-may; while the Witch-and-Sister's adoption of renegade Names suggests certain permitted latitude. To each their own. You might call this heresy. I call it friendly gossip.”\n\n[The Witch of Lagash is best known for her paintings, and for the lively 'In the Mountains…' But she also wrote two more sombre, potent volumes which were in many respect each other's mirrors.]\n\nYou've achieved the seventh degree, 'protectress', of the SKY direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "aglaophotis-skadi",
    image1: "https://imgur.com/7FZxR0m.jpg",
    image2: "https://imgur.com/oAbP4GI.jpg",
  },
  {
    id: "SK8",
    title: "The Sky In the Scar",
    text: "Each page of this book except the last bears a single sign... but the final page is empty.\n\n[[Not until there are enough here. But look around.]]\n\nYou've achieved the eighth degree, \"wise\", of the SKY direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "skadi-the-sky-in-the-scar",
    image1: "https://imgur.com/rrlVky8.jpg",
    image2: "https://imgur.com/IxwJWZb.jpg",
  },
  {
    id: "HE8b",
    title: "The Silver Hand",
    text: "It is as old I think as England. But no older.\n\n [[Not until there are enough here. But look around.]]\n\nYou’ve achieved the eighth degree, ‘otherwise’, of the HEART (b) direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "sunset-celia-the-silver-hand",
    image1: "https://imgur.com/NjgJDs7.jpg",
    image2: "https://imgur.com/bHeQ3Ho.jpg",
  },
  {
    id: "FE5b",
    title: "Christopher Strathcoyne",
    text: "For four years he served as Strathcoyne's pupil and protégé, but Illopoly's relationship with this austere and secretive man was always complicated. He wrote later: 'I still think his intentions are good. Certainly he agrees. But I never understood the final goal of his investigations. He was never prepared to enlighten me. And good intentions or not, I can no longer bear this dream of eyes. We have agreed to part, almost amicably.”\n\n[Crow and mirror, sand-sown, oak-denying]\n\nYou've achieved the fifth degree, 'visitor', of the FE (b) direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "ericapaean-christopher-strathcoyne",
    image1: "https://imgur.com/xF04tvP.jpg",
    image2: "https://imgur.com/L98xXGJ.jpg",
  },
  {
    id: "FE6a",
    title: "Eryngium",
    text: "Along the dunes by the skeleton abbey, blue-silver, black-steel.\n\n[Dr Hengerst Department of English and Philology University College of Swansea Singleton Abbey Mumbles Road Sketty Swansea]\n\nYou've achieved the sixth degree, 'flower', of the FEATHER direction of the Enigma of Secret Histories. You're entitled to use this badge wherever you like, either the full version or the transparent overlay.",
    answer: "christopher-strathcoyne-eryngium",
    image1: "https://imgur.com/dEA3p6A.jpg",
    image2: "https://imgur.com/KlCQgCk.jpg",
  },
];
